services:
  java-oauth-server:
    build:
      context: .
      dockerfile: Dockerfile.devcontainer
    ports:
      - "8080:8080"

  # TODO Local dev container
  # api:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.devcontainer
  #   ports:
  #     - "5001:5000"
  #   environment:
  #     - ASPNETCORE_ENVIRONMENT=Development

  # client:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.devcontainer
  #   # ports:
  #   #   - "5000:5000"
  #   environment:
  #     - ASPNETCORE_ENVIRONMENT=Development

  # middleWare:
  #   image: appsvc/middleware:1.3.2
  #   ports:
  #     - "8082:80"
  #   environment:
  #     - HOME = /home
  #     - WEBSITE_AUTH_ALLOWED_AUDIENCES = 
  #     - WEBSITE_AUTH_AUTO_AAD = False
  #     - WEBSITE_AUTH_CLIENT_ID = b963e9b6-134e-4c2e-a049-4d27fc9b33f3
  #     - WEBSITE_AUTH_CLIENT_SECRET = HIDDEN
  #     - WEBSITE_AUTH_DEFAULT_PROVIDER = AzureActiveDirectory
  #     - WEBSITE_AUTH_ENABLED = True
  #     - WEBSITE_AUTH_ENCRYPTION_KEY = HIDDEN
  #     - WEBSITE_AUTH_LOGOUT_PATH = /.auth/logout
  #     - WEBSITE_AUTH_OPENID_ISSUER = https://sts.windows.net/40c29545-8bca-4f51-8689-48e6819200d2/
  #     - WEBSITE_AUTH_SIGNING_KEY = HIDDEN
  #     - WEBSITE_AUTH_TOKEN_STORE = True
  #     - WEBSITE_AUTH_UNAUTHENTICATED_ACTION = RedirectToLoginPage
  #     - PORT = 80